site_name: Mindustry Wiki
site_url: https://mindustrygame.github.io/wiki-testing/
repo_url: https://github.com/MindustryGame/wiki-testing
theme: 
  name: material
  favicon: images/favicon.png
  logo: images/favicon.png
  custom_dir: overrides
extra_css:
  - 'stylesheets/style.css'
