site_name: Mindustry Wiki
site_url: https://mindustrygame.github.io/wiki-testing/
repo_url: https://github.com/MindustryGame/wiki-testing
theme: 
    name: readthedocs
    custom_dir: custom_theme/
extra_css:
  - 'stylesheets/style.css'
