site_name: Mindustry Wiki
site_url: https://mindustrygame.github.io/wiki/
repo_url: https://github.com/MindustryGame/wiki
theme: 
    name: 'mkdocs'
    custom_dir: custom_theme/
extra_css:
  - 'stylesheets/style.css'
