name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
